### ISSUE TITLE
🔥🔥  서버 시간 UTC +9 로 설정

### ISSUE THREAD

**Issue by jawsgeun** [YAPP-Github/20th-ALL-Rounder-Team-1-BE#158]
## 상세 내용
- [ ] 기능 1
- [ ] 기능 2

**Comment by jimin3263** [comment]
![image](https://user-images.githubusercontent.com/50178026/180655609-bd3075e6-1db8-4e97-8855-e7944e1475aa.png)

바꿨습니다 ~~ 🙃

**Comment by jawsgeun** [comment]
> ![image](https://user-images.githubusercontent.com/50178026/180655609-bd3075e6-1db8-4e97-8855-e7944e1475aa.png)
> 
> 바꿨습니다 ~~ 🙃

오호 그러면 서버에서는 date now 하면 kst 로 나오는 건가요~~?
어떤 설정을 바꾸신건가요?
ec2 ?

**Comment by jimin3263** [comment]
> 오호 그러면 서버에서는 date now 하면 kst 로 나오는 건가요~~? 어떤 설정을 바꾸신건가요? ec2 ?

도커 실행시 `-e TZ=Asia/Seoul` 옵션 추가하여 변경했습니다! 

도커 상에서 date 찍어서 확인,

![image](https://user-images.githubusercontent.com/50178026/181073068-f6e26528-996e-42d4-821d-40196ee2116a.png)

임시로 LocalDateTime.now() 찍는 Controller 만들어 스프링에서도 확인하였습니다~ 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/50178026/181073584-d0c761f9-4a7f-4f30-b61e-6d201eab6fee.png">

**Comment by jawsgeun** [comment]
넵 그럼 코드에 반영해주시고 해당 이슈는 close 해주세요~
